version: '3.9'
name: expense-server-api
services:
  db:
    image: postgres:15
    container_name: expense-db-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - ./volume_db_data:/var/lib/postgresql/data

volumes:
  db_data:
